# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: warmmetal/kindest-node-crio:v1.25.2-updated
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      criSocket: unix:///run/crio/crio.sock
- role: worker
  image: warmmetal/kindest-node-crio:v1.25.2-updated
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      criSocket: unix:///run/crio/crio.sock
- role: worker
  image: warmmetal/kindest-node-crio:v1.25.2-updated
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      criSocket: unix:///run/crio/crio.sock
