apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort # 或者 LoadBalancer 如果在模拟云环境中
  selector:
    app: go-hello-world
  ports:
  - port: 30007
    targetPort: 8080
    nodePort: 30008 # 如果是NodePort类型，设置一个可用端口
