apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir
  namespace: default
  labels:
    app: experiment-emptydir
spec:
  containers:
  - name: myapp-container
    image: go-hello-world-image:v0.0.1 # 使用任何您想要测试的镜像，这里以官方Nginx镜像为例
    volumeMounts:
    - mountPath: /data     # 容器内部将emptyDir挂载到/data路径
      name: temporary-storage
    command: ["/bin/sh", "-c"]
    args:
    - while true; do echo "$(date) Hello World" >> /data/output.txt; sleep 5; done # 这条命令会让容器每5秒向/data/output.txt中追加当前时间和消息
  volumes:
  - name: temporary-storage
    emptyDir: {} # 使用emptyDir卷类型
